Models/ThreadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Thread
    {
        public int userID { get; set; }
        public int topicsID { get; set; }
        public string headder { get; set; }
        public string content { get; set; }
        public string threadForfatter { get; set; }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Forum.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;
using WebApplication1.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class ForumModel : PageModel
    {
        private readonly IRepository _context;

        public ForumModel(IRepository context)
        {
            _context = context;
        }
        public IList<Topic> listOfTopics { get; set; }
        public IList<Thread> listOfThreads { get; set; }


        Repository rep = new Repository();
        public IActionResult OnGet()
        {
            
            if (Repository.loggedIn == false)
                return OnPostLogIn();
            else
            {
                listOfThreads = rep.GetAllThreads();
                listOfTopics = rep.GetAllTopics();
                
                return null;
            }
        }
        public IActionResult OnPostLogIn()
        {
            return RedirectToPage("Login");
        }
        public IActionResult OnPostLogOut()
        {
            Repository.currentLoggedInUsername = null;
            Repository.loggedIn = false;
            return OnGet();
        }
        public IActionResult OnPostNewTopic()
        {
            string _headder = Request.Form["topicHeadder"];
            string _text = Request.Form["topicText"];
            rep.CreateTopic(_headder, _text);
            return OnGet();
        }
        public IActionResult OnPostDeleteTopic()
        {
            int _topicID = Convert.ToInt32(Request.Form["_topicID"]);
            string _forfatter = Request.Form["_forfatter"];
            rep.DeleteTopic(_topicID, _forfatter);
            return OnGet();
        }
        public IActionResult OnPostNewThread()
        {
            int _topicID = Convert.ToInt32(Request.Form["_threadTopicID"]);
            string _headder = Request.Form["threadHeadder"];
            string _text = Request.Form["threadText"];
            rep.CreateThread(_topicID, _headder, _text);
            return OnGet();
        }
        public IActionResult OnPostDeleteThread()
        {
            string _ThreadHeadder = Request.Form["_ThreadHeadder"];
            string _Threadforfatter = Request.Form["_Threadforfatter"];
            rep.DeleteThread(_ThreadHeadder, _Threadforfatter);
            return OnGet();
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            if (Repository.loggedIn == false)
                return OnPostLogIn();
            else
                return null;
        }
        public IActionResult OnPostLogIn()
        {
            return RedirectToPage("Login");
        }
        public IActionResult OnPostLogOut()
        {
            Repository.currentLoggedInUsername = null;
            Repository.loggedIn = false;
            return OnGet();
        }
    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.Shared
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            Repository rep = new Repository();
            string Iusername = Request.Form["Iusername"];
            string Ipassword = Request.Form["Ipassword"];
            bool exists = rep.UserLogin(Iusername, Ipassword);
            if (exists == true)
            {
                return RedirectToPage("Index");
            }
            else
            return RedirectToPage("Login");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            if (Repository.loggedIn == false)
                return OnPostLogIn();
            else
                return null;
        }
        public IActionResult OnPostLogIn()
        {
            return RedirectToPage("Login");
        }
        public IActionResult OnPostLogOut()
        {
            Repository.currentLoggedInUsername = null;
            Repository.loggedIn = false;
            return OnGet();
        }
    }
}

Pages/SignUp.cshtml.cs
using System;
using WebApplication1;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class SignUpModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            Repository rep = new Repository();
            string Iusername = Request.Form["Iusername"];
            string Ipassword = Request.Form["Ipassword"];
            string Ifirstname = Request.Form["Ifirstname"];
            string Ilastname = Request.Form["Ilastname"];
            string Iemail = Request.Form["Iemail"];
            rep.CreateUser(Iusername, Ipassword, Ifirstname, Ilastname, Iemail);
            return RedirectToPage("Index");
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a id="google" href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Login.cshtml
@page
@model WebApplication1.Pages.Shared.LoginModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Sign In</h3>
                </div>
                <div class="card-body">
                    <form>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="username">

                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" class="form-control" placeholder="password">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn float-right login_btn">
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?<a href="#">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BestForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BestForum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Forum</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link text-dark">@WebApplication1.Repository.currentLoggedInUsername</a>
                    </li>
                    <li class="nav-item">
                        <form method="post">
                        <input type="submit" value="Log out" class="btn btn-danger" asp-page-handler="LogOut">
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BestWebForum - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/SignUp.cshtml
@page
@model WebApplication1.Pages.SignUpModel
@{
}
<!DOCTYPE html>
<html>
<head>
    <title>Sign up Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Sign up</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input name="Iusername" type="text" class="form-control" placeholder="username">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input name="Ipassword" type="password" class="form-control" placeholder="password">
                        </div>
                        <div class="input-group form-group">
                            <input name="Ifirstname" type="text" class="form-control" placeholder="First name">
                        </div>
                        <div class="input-group form-group">
                            <input name="Ilastname" type="text" class="form-control" placeholder="Last name">
                        </div>
                        <div class="input-group form-group">
                            <input name="Iemail" type="text" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="submit" onclick="" value="Create user" class="btn btn-info login_btn">
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Allready have an account?<a asp-page="Login">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>